name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (minimal)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: false  # Desativa cache para evitar busca por lockfile

      - name: Install Firebase CLI (direct)
        run: |
          # Instala sem criar node_modules ou lockfile
          npm install --global --no-package-lock firebase-tools@12.9.0
          echo "Firebase CLI installed successfully"

      - name: Prepare deployment files
        run: |
          # Cria estrutura de diretórios
          mkdir -p public
          
          # Copia index.html se existir na raiz
          if [ -f "index.html" ]; then
            cp index.html public/index.html
            echo "index.html copied to public/"
          elif [ -f "public/index.html" ]; then
            echo "index.html already in public directory"
          else
            echo "::error::index.html not found in root or public directory!"
            exit 1
          fi

      - name: Replace secrets securely
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          JSONBIN_BIN_ID: ${{ secrets.JSONBIN_BIN_ID }}
          JSONBIN_MASTER_KEY: ${{ secrets.JSONBIN_MASTER_KEY }}
          JSONBIN_ACCESS_KEY: ${{ secrets.JSONBIN_ACCESS_KEY }}
        run: |
          echo "Replacing secrets in public/index.html"
          sed -i.bak \
            -e "s|%%FIREBASE_API_KEY%%|$FIREBASE_API_KEY|g" \
            -e "s|%%FIREBASE_AUTH_DOMAIN%%|$FIREBASE_AUTH_DOMAIN|g" \
            -e "s|%%FIREBASE_PROJECT_ID%%|$FIREBASE_PROJECT_ID|g" \
            -e "s|%%FIREBASE_STORAGE_BUCKET%%|$FIREBASE_STORAGE_BUCKET|g" \
            -e "s|%%FIREBASE_MESSAGING_SENDER_ID%%|$FIREBASE_MESSAGING_SENDER_ID|g" \
            -e "s|%%FIREBASE_APP_ID%%|$FIREBASE_APP_ID|g" \
            -e "s|%%JSONBIN_BIN_ID%%|$JSONBIN_BIN_ID|g" \
            -e "s|%%JSONBIN_MASTER_KEY%%|$JSONBIN_MASTER_KEY|g" \
            -e "s|%%JSONBIN_ACCESS_KEY%%|$JSONBIN_ACCESS_KEY|g" \
            public/index.html
          
          # Verificação adicional
          if grep -q '%%' public/index.html; then
            echo "::error::Some placeholders were not replaced!"
            exit 1
          fi
          rm -f public/index.html.bak

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
