name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Replace secrets
      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        JSONBIN_BIN_ID: ${{ secrets.JSONBIN_BIN_ID }}
        JSONBIN_MASTER_KEY: ${{ secrets.JSONBIN_MASTER_KEY }}
        JSONBIN_ACCESS_KEY: ${{ secrets.JSONBIN_ACCESS_KEY }}
      run: |
        mkdir -p public
        cp index.html public/index.html || true
        sed -i "s|%%FIREBASE_API_KEY%%|$FIREBASE_API_KEY|g" public/index.html
        sed -i "s|%%FIREBASE_AUTH_DOMAIN%%|$FIREBASE_AUTH_DOMAIN|g" public/index.html
        sed -i "s|%%FIREBASE_PROJECT_ID%%|$FIREBASE_PROJECT_ID|g" public/index.html
        sed -i "s|%%FIREBASE_STORAGE_BUCKET%%|$FIREBASE_STORAGE_BUCKET|g" public/index.html
        sed -i "s|%%FIREBASE_MESSAGING_SENDER_ID%%|$FIREBASE_MESSAGING_SENDER_ID|g" public/index.html
        sed -i "s|%%FIREBASE_APP_ID%%|$FIREBASE_APP_ID|g" public/index.html
        sed -i "s|%%JSONBIN_BIN_ID%%|$JSONBIN_BIN_ID|g" public/index.html
        sed -i "s|%%JSONBIN_MASTER_KEY%%|$JSONBIN_MASTER_KEY|g" public/index.html
        sed -i "s|%%JSONBIN_ACCESS_KEY%%|$JSONBIN_ACCESS_KEY|g" public/index.html

    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
        entryPoint: '.'  # Indica que firebase.json está na raiz
