name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@12.9.0

      - name: Create minimal package.json
        if: !exists('package.json')
        run: echo '{"name":"noc-backlog","private":true}' > package.json

      - name: Prepare public directory
        run: |
          mkdir -p public
          if [ -f "index.html" ]; then
            cp index.html public/index.html
          elif [ -f "public/index.html" ]; then
            echo "index.html already in public/"
          else
            echo "Error: index.html not found!" && exit 1
          fi

      - name: Replace environment secrets
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          JSONBIN_BIN_ID: ${{ secrets.JSONBIN_BIN_ID }}
          JSONBIN_MASTER_KEY: ${{ secrets.JSONBIN_MASTER_KEY }}
          JSONBIN_ACCESS_KEY: ${{ secrets.JSONBIN_ACCESS_KEY }}
        run: |
          sed -i.bak \
            -e "s|%%FIREBASE_API_KEY%%|$FIREBASE_API_KEY|g" \
            -e "s|%%FIREBASE_AUTH_DOMAIN%%|$FIREBASE_AUTH_DOMAIN|g" \
            -e "s|%%FIREBASE_PROJECT_ID%%|$FIREBASE_PROJECT_ID|g" \
            -e "s|%%FIREBASE_STORAGE_BUCKET%%|$FIREBASE_STORAGE_BUCKET|g" \
            -e "s|%%FIREBASE_MESSAGING_SENDER_ID%%|$FIREBASE_MESSAGING_SENDER_ID|g" \
            -e "s|%%FIREBASE_APP_ID%%|$FIREBASE_APP_ID|g" \
            -e "s|%%JSONBIN_BIN_ID%%|$JSONBIN_BIN_ID|g" \
            -e "s|%%JSONBIN_MASTER_KEY%%|$JSONBIN_MASTER_KEY|g" \
            -e "s|%%JSONBIN_ACCESS_KEY%%|$JSONBIN_ACCESS_KEY|g" \
            public/index.html
          rm -f public/index.html.bak

      - name: Verify files before deploy
        run: |
          ls -la public/
          grep -E '%%[A-Z_]+%%' public/index.html && exit 1 || echo "All secrets replaced successfully"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
          target: 'https://backlogproeqtl.web.app/'  
