name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (minimal)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          # Removida completamente a linha do cache

      - name: Install Firebase CLI (no lockfile)
        run: |
          echo "Installing Firebase CLI without generating lockfile..."
          npm install --global --no-package-lock firebase-tools@12.9.0
          firebase --version

      - name: Prepare deployment files
        run: |
          mkdir -p public
          
          if [ -f "index.html" ]; then
            cp index.html public/index.html
            echo "✓ index.html copied to public/"
          elif [ -f "public/index.html" ]; then
            echo "✓ index.html already in public directory"
          else
            echo "::error::index.html not found in root or public directory!"
            exit 1
          fi

      - name: Replace environment secrets
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          JSONBIN_BIN_ID: ${{ secrets.JSONBIN_BIN_ID }}
          JSONBIN_MASTER_KEY: ${{ secrets.JSONBIN_MASTER_KEY }}
          JSONBIN_ACCESS_KEY: ${{ secrets.JSONBIN_ACCESS_KEY }}
        run: |
          echo "🔒 Replacing secrets in public/index.html..."
          sed -i.bak \
            -e "s|%%FIREBASE_API_KEY%%|$FIREBASE_API_KEY|g" \
            -e "s|%%FIREBASE_AUTH_DOMAIN%%|$FIREBASE_AUTH_DOMAIN|g" \
            -e "s|%%FIREBASE_PROJECT_ID%%|$FIREBASE_PROJECT_ID|g" \
            -e "s|%%FIREBASE_STORAGE_BUCKET%%|$FIREBASE_STORAGE_BUCKET|g" \
            -e "s|%%FIREBASE_MESSAGING_SENDER_ID%%|$FIREBASE_MESSAGING_SENDER_ID|g" \
            -e "s|%%FIREBASE_APP_ID%%|$FIREBASE_APP_ID|g" \
            -e "s|%%JSONBIN_BIN_ID%%|$JSONBIN_BIN_ID|g" \
            -e "s|%%JSONBIN_MASTER_KEY%%|$JSONBIN_MASTER_KEY|g" \
            -e "s|%%JSONBIN_ACCESS_KEY%%|$JSONBIN_ACCESS_KEY|g" \
            public/index.html
          
          echo "✅ Secret replacement completed"
          rm -f public/index.html.bak

          # Verificação final
          if grep -q '%%' public/index.html; then
            echo "::error::Some placeholders were not replaced!"
            exit 1
          fi

      - name: Verify deployment files
        run: |
          echo "📂 Deployment files:"
          ls -la public/
          echo -e "\n🔍 Checking index.html:"
          head -n 20 public/index.html

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
