name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Configure Firebase
        run: firebase use --token ${{ secrets.FIREBASE_TOKEN }}
      
      - name: Replace environment variables
        run: |
          sed -i "s|%%FIREBASE_API_KEY%%|${{ secrets.FIREBASE_API_KEY }}|g" public/firebase-config.js
          sed -i "s|%%FIREBASE_AUTH_DOMAIN%%|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" public/firebase-config.js
          sed -i "s|%%FIREBASE_PROJECT_ID%%|${{ secrets.FIREBASE_PROJECT_ID }}|g" public/firebase-config.js
          sed -i "s|%%FIREBASE_STORAGE_BUCKET%%|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" public/firebase-config.js
          sed -i "s|%%FIREBASE_MESSAGING_SENDER_ID%%|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" public/firebase-config.js
          sed -i "s|%%FIREBASE_APP_ID%%|${{ secrets.FIREBASE_APP_ID }}|g" public/firebase-config.js
          sed -i "s|%%JSONBIN_BIN_ID%%|${{ secrets.JSONBIN_BIN_ID }}|g" public/firebase-config.js
          sed -i "s|%%JSONBIN_MASTER_KEY%%|${{ secrets.JSONBIN_MASTER_KEY }}|g" public/firebase-config.js
          sed -i "s|%%JSONBIN_ACCESS_KEY%%|${{ secrets.JSONBIN_ACCESS_KEY }}|g" public/firebase-config.js
      
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}