name: Deploy to Firebase

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Replace Secrets in Config
        run: |
          sed -i "s/FIREBASE_API_KEY_PLACEHOLDER/${{ secrets.FIREBASE_API_KEY }}/g" public/js/config.js
          sed -i "s/FIREBASE_AUTH_DOMAIN_PLACEHOLDER/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" public/js/config.js
          sed -i "s/FIREBASE_PROJECT_ID_PLACEHOLDER/${{ secrets.FIREBASE_PROJECT_ID }}/g" public/js/config.js
          sed -i "s/FIREBASE_STORAGE_BUCKET_PLACEHOLDER/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" public/js/config.js
          sed -i "s/FIREBASE_MESSAGING_SENDER_ID_PLACEHOLDER/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" public/js/config.js
          sed -i "s/FIREBASE_APP_ID_PLACEHOLDER/${{ secrets.FIREBASE_APP_ID }}/g" public/js/config.js
          
          sed -i "s/JSONBIN_BIN_ID_PLACEHOLDER/${{ secrets.JSONBIN_BIN_ID }}/g" public/js/config.js
          sed -i "s/JSONBIN_MASTER_KEY_PLACEHOLDER/${{ secrets.JSONBIN_MASTER_KEY }}/g" public/js/config.js
          sed -i "s/JSONBIN_ACCESS_KEY_PLACEHOLDER/${{ secrets.JSONBIN_ACCESS_KEY }}/g" public/js/config.js

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token $FIREBASE_TOKEN
