
name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: npm install
      
    - name: Replace environment variables
      run: |
        sed -i "s/FIREBASE_API_KEY_PLACEHOLDER/${{ secrets.FIREBASE_API_KEY }}/g" public/js/config.js
        sed -i "s/FIREBASE_APP_ID_PLACEHOLDER/${{ secrets.FIREBASE_APP_ID }}/g" public/js/config.js
        sed -i "s/FIREBASE_AUTH_DOMAIN_PLACEHOLDER/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" public/js/config.js
        sed -i "s/FIREBASE_MESSAGING_SENDER_ID_PLACEHOLDER/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" public/js/config.js
        sed -i "s/FIREBASE_PROJECT_ID_PLACEHOLDER/${{ secrets.FIREBASE_PROJECT_ID }}/g" public/js/config.js
        sed -i "s/FIREBASE_STORAGE_BUCKET_PLACEHOLDER/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" public/js/config.js
        sed -i "s/JSONBIN_ACCESS_KEY_PLACEHOLDER/${{ secrets.JSONBIN_ACCESS_KEY }}/g" public/js/config.js
        sed -i "s/JSONBIN_BIN_ID_PLACEHOLDER/${{ secrets.JSONBIN_BIN_ID }}/g" public/js/config.js
        sed -i "s/JSONBIN_MASTER_KEY_PLACEHOLDER/${{ secrets.JSONBIN_MASTER_KEY }}/g" public/js/config.js
        
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
